"""Builds `Citation` records strictly from retrieval metadata — never
free-generated by the model (DOMAIN_MODEL.md §4.8 invariant, PRD §10 risk
"citation hallucination").
"""

from app.domains.knowledge.schemas import TranscriptChunkRead
from app.domains.skills.schemas import CitationRef


class CitationBuilder:
    """Stateless — a class only to match the project's constructor-based DI
    convention and allow future configuration (e.g. label formatting)."""

    def build(self, *, retrieved_chunks: list[TranscriptChunkRead]) -> list[CitationRef]:
        """Map retrieved chunks to `CitationRef`s, one per chunk, in the
        same order they were passed to the model (see
        `qa/prompts.py::build_qa_prompt`'s excerpt numbering)."""

        return [
            CitationRef(
                transcript_chunk_id=chunk.id,
                display_label=self._format_label(chunk),
                excerpt=chunk.content,
            )
            for chunk in retrieved_chunks
        ]

    @staticmethod
    def _format_label(chunk: TranscriptChunkRead) -> str:
        """e.g. "Episode 142 — 12:34-13:02", matching DATABASE_SCHEMA.md's
        `citations.display_label` column comment. Falls back gracefully if
        episode metadata wasn't joined in (shouldn't happen in practice —
        `KnowledgeRepository.similarity_search` always eager-loads it)."""

        episode_title = chunk.episode.title if chunk.episode else "Unknown episode"
        start = _format_timestamp(chunk.start_timestamp_seconds)
        end = _format_timestamp(chunk.end_timestamp_seconds)
        return f"{episode_title} — {start}-{end}"


def _format_timestamp(total_seconds: int) -> str:
    hours, remainder = divmod(max(total_seconds, 0), 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{seconds:02d}"
    return f"{minutes}:{seconds:02d}"
